### ISSUE TITLE
Document how to start the Kudu deamons

### ISSUE THREAD

**Issue by davidonlaptop** [GELOG/docker-ubuntu-kudu#1]
Starting the master yields this error:

```
docker run --rm -ti kudu
root@180b7de1ce0a:/# kudu-master
F1006 02:32:24.711573    14 master_main.cc:53] Check failed: _s.ok() Bad status: Service unavailable: Clock is not synchronized: Error reading clock. Clock considered unsynchronized. Errno: Invalid argument
*** Check failure stack trace: ***
    @     0x7f3bb7779ffd  google::LogMessage::Fail()
    @     0x7f3bb777bfa9  google::LogMessage::SendToLog()
    @     0x7f3bb7779bc2  google::LogMessage::Flush()
    @     0x7f3bb777c93f  google::LogMessageFatal::~LogMessageFatal()
    @           0x402b0d  kudu::master::MasterMain()
    @           0x402e8f  main
    @     0x7f3bb6eb0ec5  (unknown)
    @           0x402709  (unknown)
    @              (nil)  (unknown)
Aborted
```

Starting the TabletServer yields a similar error:

```
root@180b7de1ce0a:/# kudu-tserver
F1006 02:33:44.813959    16 tablet_server_main.cc:49] Check failed: _s.ok() Bad status: Service unavailable: Clock is not synchronized: Error reading clock. Clock considered unsynchronized. Errno: Invalid argument
*** Check failure stack trace: ***
    @     0x7f98020a6ffd  google::LogMessage::Fail()
    @     0x7f98020a8fa9  google::LogMessage::SendToLog()
    @     0x7f98020a6bc2  google::LogMessage::Flush()
    @     0x7f98020a993f  google::LogMessageFatal::~LogMessageFatal()
    @           0x402b30  kudu::tserver::TabletServerMain()
    @           0x402eb2  main
    @     0x7f98017ddec5  (unknown)
    @           0x402729  (unknown)
    @              (nil)  (unknown)
Aborted
```

**Comment by danburkert** [comment]
In the default (recommended) configuration, Kudu requires NTP to be running, and for the clock to be synchronized.  If NTP is configured correctly, the `ntptime` command should return something like  `ntp_gettime() returns code 0 (OK)` as the first line.  The [Kudu docs](http://getkudu.io/docs/troubleshooting.html#ntp) go into a bit more detail.  I'm not familiar with how to best setup containers to use NTP.

**Comment by davidonlaptop** [comment]
The Docker container clock is synchronized with the docker host clock, since they share the same kernel. But there is no NTP process running inside the container. Typically, in ideal Docker world there should a single process per container, or a parent process with multiple child processes. There is a way around this, but it breaks a bit Docker's main purpose.

Does NTP require a daemon to be running or can it connect to a distant server?

**Comment by jdcryans** [comment]
Hybrid clock needs to know what the clock error is, can't do that with just a system clock. You may have to shut it off using --use_hybrid_clock=false which in this context should be mostly fine.

**Comment by toddlipcon** [comment]
What I'm surprised about is this: inside the docker container, the ntp_gettime function should just use the normal adjtimex() system call, which would be handled by the host kernel. So, if NTP is running correctly on the host, then Kudu should work fine inside the container with hybrid clock.

**Comment by davidonlaptop** [comment]
Hum, it may because I'm running Docker on OSX (via Docker-Machine / VirtualBox).

http://stackoverflow.com/questions/22800624/will-docker-container-auto-sync-time-with-the-host-machine

**Comment by davidonlaptop** [comment]
@jdcryans It seems like disabling the hybrid clock is going further: 

```
root@d0224d9bfc3d:/# kudu-master --use_hybrid_clock=false
F1006 05:52:23.440083    64 master_main.cc:53] Check failed: _s.ok() Bad status: IO error: Failed to load FS layout: Write-ahead log directory (fs_wal_dir) not provided

root@d0224d9bfc3d:/# kudu-master --use_hybrid_clock=false -fs_wal_dir /tmp
F1006 05:54:23.673264    68 master_main.cc:53] Check failed: _s.ok() Bad status: Already present: Could not create new FS layout: FSManager root is not empty: /tmp
```

**Comment by davidonlaptop** [comment]
ah `kudu-master --use_hybrid_clock=false -fs_wal_dir /data` seems to work, got no output however.

**Comment by toddlipcon** [comment]
Yea, if you're just using a single node, turning off hybrid clock is fine, but isn't great if you plan to run on a cluster.

It's expected to get no output -- it's a daemon... is it not staying running? Nothing available no the web UI? (port 8051)

**Comment by davidonlaptop** [comment]
> Yea, if you're just using a single node, turning off hybrid clock is fine, but isn't great if you plan to run on a cluster.

I haven't played much with the system clocks, but I can the imagine the impact it can have on a distributed system.

> It's expected to get no output -- it's a daemon... is it not staying running? Nothing available no the web UI? (port 8051)

HDFS outputs to stdout by default. I probably run just fine, let me check the GUI.

**Comment by davidonlaptop** [comment]
where is the default log directory ?

**Comment by toddlipcon** [comment]
If you prefer output,you can use --logtostderr. Otherwise, it will create log files.

**Comment by toddlipcon** [comment]
I believe it defaults to /tmp

**Comment by davidonlaptop** [comment]
I get connection refused on the web UI.

But there is logs into /tmp.

**Comment by toddlipcon** [comment]
One thing that we ran into is that if you are using aufs with docker, it doesn't play nicely with some operations like renaming directories. If you set up docker volumes, and point Kudu's data directories at the volumes, it works OK.
https://github.com/cloudera/kudu-examples/wiki/Docker-based-tutorial has an old tutorial I wrote (that Dockerfile did an apt-get install rather than a build from source)

**Comment by davidonlaptop** [comment]
Web UI works for Kudu Master!!

**Comment by davidonlaptop** [comment]
It works:

```
docker run -d --name kudu-master \
    -p 8050:8050 -p 8051:8051 \
    kudu kudu-master --use_hybrid_clock=false --logtostderr -fs_wal_dir /data && \
docker logs -f kudu-master
```

```
docker exec -ti kudu-master kudu-tserver --use_hybrid_clock=false --logtostderr -fs_wal_dir /data-tserver
```

```
docker exec -ti kudu-master kudu-ts-cli status
```

**Comment by davidonlaptop** [comment]
Is there a command I can run to try writing data without Impala ?

**Comment by jdcryans** [comment]
David, your latest question can beneficiate from a broader audience and it's not too related to "documenting how to start daemons", mind taking this back to the user mailing list?

**Comment by davidonlaptop** [comment]
sure!

Thanks @danburkert @jdcryans @toddlipcon , I've created separate tickets in this repo for the remaining issue, and will post the image in mailing list.

**Comment by ramjaddu** [comment]
@davidonlaptop , Thank you very much for the answer      kudu-master --use_hybrid_clock=false 
I was struggling solve time sync problem.

**Comment by davidonlaptop** [comment]
you're welcome!

**Comment by sundbp** [comment]
For future readers: if your docker hosts has synced clocks via ntp, then running kudu in a container on such a host you can just give the container the privileges to use these syscalls and it'll work fine running a 1 process docker container of kud-master or kudu-tserver. You can pass --privileged or add just the time capability.

**Comment by davidonlaptop** [comment]
Thanks @sundbp!

It's a good point. Keep in mind though that running the container in
privileged mode will give the container access to all devices by default.

https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities

**Comment by sundbp** [comment]
Yeah. One could just give it CAP_SYS_TIME as well, that should be enough
for the syscall underlying ntp_gettime() to be allowed.

**Comment by sadeshjayraj** [comment]
Hi all,

I am using Yugabyte 1.0.1.0 ,I have installed it on 3 data center servers which includes 9 servers, 3 from each data center 

But after starting master service on server, I am getting error : Leader does not have a valid lease. (yb/common/wire_protocol.cc:190): Old leader may have hybrid time lease, while adding: WRITE_OP

Before running above command I have set --use_hybrid_clock=false and it does not look helpful.

If I try to start master service without changing parameter use_hybrid_clock then after starting master service i am getting error like "clock unsynchronised 65"

**Comment by davidonlaptop** [comment]
Hi Sadesh,

I am not sure to understand the link between Yugabyte and Kudu. Are you
using this docker image?

-D

**Comment by sadeshjayraj** [comment]
Hello David,

 I am facing same issue related with parameter --use_hybrid_clock=false in Yugabyte application.This is not related with Kudu.

I am looking solution for the same.

**Comment by davidonlaptop** [comment]
Are you using Yugabyte within docker or a virtual machine?

**Comment by sadeshjayraj** [comment]
No, I have installed it on physical machine.
But we can avoid such ntp issue by doing following setting in all servers

Stop application server 
run given command on all servers for enabling and synchronizing  the ntp
timedatectl set-local-rtc 0

timedatectl set-ntp 0 

Also check 
cat /etc/resolv.conf
It should contain only one name  server 
nameserver **********

Once its done take restart of ntp service

service ntpd stop
ntpd -gq
service ntpd start
ntptime

then start the app server

**Comment by davidonlaptop** [comment]
cool!

glad you found the issue
